name: Build and Upload CPython MSI

on:
  workflow_dispatch: 

jobs:

  build_windows_msi:
      name: Windows MSI${{ '' }}
      strategy:
        matrix:
          arch:
          - x86
          - x64
          - arm64
      runs-on: windows-latest
      env:
        IncludeFreethreaded: true
      steps:
      - uses: actions/checkout@v4
      - name: Build CPython installer
        run: .\Tools\msi\build.bat --doc -${{ matrix.arch }}
  
      # 추가적인 스텝
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-msi-${{ matrix.arch }}
          path: ./PCbuild/**/python-*.exe  # MSI 빌드 결과물 업로드
